meta_trader:
  terminal_path: "C:\\Windows\\System32\\cmd.exe"  # Update with your terminal path
  login:57169911                 # Your MT5 account login
  password:@Kinghuncho1         # Your account password
  server:HFMarketsKE-Demo2       # Your broker's server address

bot:
  symbol: "EURUSD"
  strategy: "short_term"  # Options: short_term, medium_term, long_term
  risk_percentage: 1
  dynamic_settings: true

